### ISSUE TITLE
Undetected hooks?

### ISSUE THREAD

**Issue by Jeimy041** [auraGB/aurawareSelfLeak#1]
Title says all

**Comment by dowan1995** [comment]
So do U want use it in FACEIT or ?

**Comment by dowan1995** [comment]
> Title says all

So do U want use it in FACEIT or ?

**Comment by Jeimy041** [comment]
Well, not really I want to get onto a high rank by legit hacking. I used to do this with Indigo but it´s hooks got detected and after the last update I got bored because I had to update the full source.

**Comment by auraGB** [comment]
Please dont use this cheat for esea or faceit no where did i say it is safe for these anti cheats. This is just basic VMTHooking which is updated and fine to use on MM ( VAC ) servers.
Aslong as you change the cheats code a bit ( recode some features ) than you should be fine.

**Comment by auraGB** [comment]
> Well, not really I want to get onto a high rank by legit hacking. I used to do this with Indigo but it´s hooks got detected and after the last update I got bored because I had to update the full source.

Please dont use this cheat for esea or faceit no where did i say it is safe for these anti cheats. This is just basic VMTHooking which is updated and fine to use on MM ( VAC ) servers.
Aslong as you change the cheats code a bit ( recode some features ) than you should be fine.
